version: '3'
services:
  web:
    build: ./front/global/
    ports:
      - "8080:80"
    depends_on:
      - gateway

  gateway:
    build:
      context: ./gateway/
      args:
        - JAR_FILE=./gateway-0.0.1-SNAPSHOT.jar
        - PROFILE=prod
    ports:
      - "5555:5555"
    depends_on:
      - register


  register:
    build:
      context: ./register/
      args:
        - JAR_FILE=./registry-server-0.0.1-SNAPSHOT.jar
        - PROFILE=prod
    ports:
      - "8761:8761"

  redis:
    image: redis:latest

  global:
    build:
      context: ./global/
      args:
        - JAR_FILE=./global-0.0.1-SNAPSHOT.jar
    depends_on:
      - mysql
      - register
      - gateway
      - redis

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
     - ./db:/docker-entrypoint-initdb.d/
     - ./db:/etc/mysql/conf.d
    ports:
      - "3306:3306"
