version: '3'
services:
  web:
    build: ./front/global/
    ports:
      - "8080:80"
    depends_on:
      - gateway

  gateway:
    build:
      context: ./gateway/
      args:
        - JAR_FILE=./gateway-0.0.1-SNAPSHOT.jar
        - PROFILE=prod
    ports:
      - "5555:5555"
    depends_on:
      - register


  register:
    build:
      context: ./register/
      args:
        - JAR_FILE=./registry-server-0.0.1-SNAPSHOT.jar
        - PROFILE=prod
    ports:
      - "8761:8761"