server:
  port: 8082
spring:
  application:
    name: global
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://mysql:3306/his_menzhen?useUnicode=true&characterEncoding=utf8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
    password:
eureka:
  client:
    service-url:
      defaultZone: http://register:8761/eureka
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 启动feign的熔断器功能


